### ISSUE TITLE
JAGS errors: Dimension mismatch

### ISSUE THREAD

**Issue by Flynn-stagram** [zhenkewu/baker#22] opened 2023-05-17 10:34 UTC
Hello, 
I am trying to run your model using only the vignette code, and get the following error when trying to fit the model (using the function nplcm()):

Welcome to JAGS 4.3.1 (official binary) on Wed May 17 06:31:21 2023
JAGS is free software and comes with ABSOLUTELY NO WARRANTY
Loading module: basemod: ok
Loading module: bugs: ok
Deleting model
Clearing data table 
Reading data file jagsdata.txt
Compiling model graph
   Resolving undeclared variables
Deleting model
RUNTIME ERROR:
Compilation error on line 32.
Dimension mismatch in subset expression of MBS_1
Warning: cannot open file 'CODAindex.txt': No such file or directoryError in file(file, "rt") : cannot open the connection

Please advise how to resolve.

**Comment by wagnerbd** [comment] 2023-10-26 03:48
I also receive the same error when running the vignette code and the code provided in the following directory:
[baker_example](https://github.com/zhenkewu/baker_example/tree/master)
/simulated_example_nplcm.R 

Any help would be much appreciated.


Welcome to JAGS 4.3.1 on Wed Oct 25 21:42:44 2023
JAGS is free software and comes with ABSOLUTELY NO WARRANTY
Loading module: basemod: ok
Loading module: bugs: ok
Deleting model
Clearing data table 
Reading data file jagsdata.txt
Compiling model graph
   Resolving undeclared variables
RUNTIME ERROR:
Compilation error on line 32.
Dimension mismatch in subset expression of MBS_1
Deleting model
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'CODAindex.txt': No such file or directory

**Comment by zhenkewu** [comment] 2023-10-26 04:05
Thanks for the note. I can reproduce the error and will look into it and drop a note when fixed.

**Comment by xueyaoliang** [comment] 2023-12-08 12:39
Hello, I also receive the same error when running the code. But I was able to run it last month with my real world NP measurement data. I don't konw if it is the update of R software version (M1 Macbook) of late.

Any help would be much appreciated.

Welcome to JAGS 4.3.1 (official binary) on Fri Dec  8 13:33:43 2023
JAGS is free software and comes with ABSOLUTELY NO WARRANTY
Loading module: basemod: ok
Loading module: bugs: ok
Deleting model
Clearing data table 
Reading data file jagsdata.txt
Compiling model graph
   Resolving undeclared variables
RUNTIME ERROR:
Compilation error on line 32.
Dimension mismatch in subset expression of MBS_1
Deleting model
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'CODAindex.txt': No such file or directory

**Comment by zhenkewu** [comment] 2023-12-14 11:22
@xueyaoliang @wagnerbd @Flynn-stagram  Hi everyone, sorry for the delay. I was able to fix the issue in the current version of 1.0.2. You may consider installing JAGS 4.3.2 if you are using Apple M1 Chip or higher, or if you are using R 4.3.x. 

Could you please try `example(nplcm)` and see if the simulated example works now? You may need to re-install the package from github. 

I am also in the process of doing Github Actions and Re-Submitting to CRAN, which may take some additional fixing for getting the build under other OS's working. 

### Notes on Debugging for upgrading to baker 1.0.2

### Details:

- added code to change how a matrix is represented as data input for JAGS. In particular, `, dim=(600,6)` to `, .Dim=(600,6)`. This issue is caused by the `dump()` function only producing the former, while the JAGS 4.3.2 only accepts the latter format.
- removed `cut`
- removed the lower and upper limits in `I(,)`



### JAGS 4.3.2, Newer Version of R, and Apple Silicon

- [Error loading `rjag`](https://stackoverflow.com/questions/70533673/error-package-or-namespace-load-failed-for-rjags)
- [Install JAGS for Apple computers with M1 chips](https://sourceforge.net/p/mcmc-jags/support-requests/8/)
  - Install `JAGS-4.3.2.pkg` for compatibility with R version 4.3.0 and later
  - > These are the available builds of JAGS for macOS.  The vast majority of users will want to use one of the following two installers:
    > - JAGS-4.3.2.pkg for compatibility with R version 4.3.0 and later
    > - JAGS-4.3.1.pkg for compatibility with R versions 4.0.x to 4.2.x
    > These are signed universal (x86_64 + arm64) package installers of JAGS versions 4.3.1 & 4.3.2 that have been built for binary
    compatability with the official macOS builds of R. Note that there is no difference between JAGS versions 4.3.1 and 4.3.2 other than the binary compatibility with different versions of R, so you should pick the version of JAGS that matches your version of R. If you do not use R then you can use either version (although note the minimum requirement of macOS 11 "Big Sur" for JAGS-4.3.2, compared to macOS 10.13 "High Sierra" for JAGS-4.3.1). For architecture-specific (unsigned) builds, as well as details of the build process used, see the extras folder.

**Comment by xueyaoliang** [comment] 2023-12-19 10:11
Thank you Zhenke, baker 1.0.2 works! 

I tried `example(nplcm)` and NPLCM without regression (BrS and SS data), the simulated example works fine.

```
 nplcm_noreg <- nplcm(data_nplcm_noreg, model_options_no_reg,mcmc_options_no_reg)
```

> ==[baker] Results stored in: == 
>  ~/Downloads/2023_12_19_no_reg/results 
> Welcome to JAGS 4.3.2 (official binary) on Tue Dec 19 17:55:31 2023
> JAGS is free software and comes with ABSOLUTELY NO WARRANTY
> Loading module: basemod: ok
> Loading module: bugs: ok
> Deleting model
> Clearing data table 
> Reading data file jagsdata.txt
> Compiling model graph
>    Resolving undeclared variables
>    Allocating nodes
> Graph information:
>    Observed stochastic nodes: 3600
>    Unobserved stochastic nodes: 5429
>    Total graph size: 59517
> Reading initial values file jagsinits1.txt
> Initializing model
> Updating 100
> -------------------------| 100
> ************************* 100%
> Updating 100
> -------------------------| 100
> ************************* 100%

But when I further tried NPLCM with regression (Non-nested and nested models), another error came up and the model doesn’t fit any more:

```
nplcm_reg_nonest_strat <- nplcm(data_nplcm_reg_nest_strat,model_options_reg_nonest_strat, mcmc_options_reg_nonest_strat)
```

> ==[baker] Results stored in: == 
>  ~/Downloads/2023_12_19_reg_nonest_strat/results 
> Welcome to JAGS 4.3.2 (official binary) on Tue Dec 19 17:53:38 2023
> JAGS is free software and comes with ABSOLUTELY NO WARRANTY
> Loading module: basemod: ok
> Loading module: bugs: ok
> Deleting model
> Clearing data table 
> Reading data file jagsdata.txt
> syntax error
> Error in file(file, "rt") : cannot open the connection
> In addition: Warning message:
> In file(file, "rt") :
>   cannot open file 'CODAindex.txt': No such file or directory


I don't know if there is anything else that needs to be fine-tuned in the model. 
I would really appreciate your further help.

Thank you！

**Comment by zhenkewu** [comment] 2023-12-19 13:21
@xueyaoliang could you please try again? I updated the package so that it runs now. 

I am also attaching an R markdown file which is a software paper to go along with `baker`. 

![Screenshot 2023-12-19 at 8 19 01 AM](https://github.com/zhenkewu/baker/assets/4580992/0320c8c2-0b81-426f-9af6-163b17987c97)

**Comment by zhenkewu** [comment] 2023-12-19 13:31
@xueyaoliang [here](https://zhenkewu.com/assets/html/baker_vignette.html#) is the link to the compiled Rmd file that contains tests for all scenarios. Could you also indicate which files are you running the `nplcm_reg_nonest_strat` example that caused you problem earlier.

**Comment by xueyaoliang** [comment] 2023-12-19 14:19
Yes, I basically run the whole [rmd file ](https://zhenkewu.com/assets/html/baker_vignette.html#)thorough, and it works fine on `nplcm_noreg` and `nplcm_noreg_with_SS`, until `nplcm_reg_nonest_strat` goes wrong.
Have you just updated a new version of baker package? Maybe I'll re-install the package to see if it works, because github doesn't seem to be able to remotely install baker for a while.
![zhenke](https://github.com/zhenkewu/baker/assets/37697047/a0446c6e-5d06-4852-9842-8f0ddae461ec)

**Comment by zhenkewu** [comment] 2023-12-19 14:37
Thanks! Yes, I updated this just now again to make sure. I wonder if you may reload R or uninstall baker first before you reinstall?

**Comment by xueyaoliang** [comment] 2023-12-19 15:26
Thanks very much! The new version of baker works perfectly! 
![works!](https://github.com/zhenkewu/baker/assets/37697047/f86b36aa-bc7a-4daf-b59c-7c6fa0d30414)

**Closed** 2023-12-19 16:32 UTC
